# Generated by Django 4.1.10 on 2024-01-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=254, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден?'),
        ),
    ]
