# Generated by Django 4.2.6 on 2023-11-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(to='cars.vehicle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agreement_accepted',
            field=models.BooleanField(default=False, verbose_name='Пользовательское соглашение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users_images', verbose_name='Аватар'),
        ),
    ]
