# Generated by Django 4.2.6 on 2023-11-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cars_alter_user_agreement_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cars',
        ),
    ]
