# Generated by Django 4.2.6 on 2023-11-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regnum', models.CharField(db_index=True, max_length=10, verbose_name='Регистрационный знак')),
                ('IsRegnumAlien', models.BooleanField(default=False, verbose_name='Иностранный?')),
                ('Model', models.CharField(max_length=200, verbose_name='Модель')),
                ('Color', models.CharField(default=None, max_length=200, verbose_name='Цвет')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('Updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ('Regnum',),
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_brand', models.CharField(max_length=100, verbose_name='Марка ТС')),
            ],
            options={
                'verbose_name': 'Марка ТС',
                'verbose_name_plural': 'Марка ТС',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('icon', models.ImageField(upload_to='img_category', verbose_name='Путь до иконки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=255, verbose_name='Модель ТС')),
            ],
            options={
                'verbose_name': 'Модель ТС',
                'verbose_name_plural': 'Модель ТС',
            },
        ),
    ]
