# Generated by Django 4.1.10 on 2023-12-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnum', models.CharField(db_index=True, max_length=10, verbose_name='Регистрационный знак')),
                ('is_alien', models.BooleanField(default=False, verbose_name='Иностранный?')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('color', models.CharField(default=None, max_length=200, verbose_name='Цвет')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ('regnum',),
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_brand', models.CharField(max_length=100, verbose_name='Марка ТС')),
            ],
            options={
                'verbose_name': 'Марка ТС',
                'verbose_name_plural': 'Марка ТС',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('icon', models.ImageField(upload_to='img_category', verbose_name='Путь до иконки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=255, verbose_name='Модель ТС')),
            ],
            options={
                'verbose_name': 'Модель ТС',
                'verbose_name_plural': 'Модель ТС',
            },
        ),
    ]
