# Generated by Django 4.2.6 on 2023-11-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Model',
            field=models.CharField(max_length=200, verbose_name='Модель'),
        ),
    ]
