# Generated by Django 4.2.6 on 2023-11-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_vehicle_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='drivers',
        ),
    ]
