# Generated by Django 4.1.10 on 2023-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_vehicle_category_vehiclecategory_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclecategory',
            options={'verbose_name': 'Категория ТС', 'verbose_name_plural': 'Категории ТС'},
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='img_category', verbose_name='Путь до иконки'),
        ),
    ]
