# Generated by Django 4.1.10 on 2023-12-08 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0005_alter_vehiclecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Водители'),
        ),
    ]
