# Generated by Django 4.1.10 on 2023-12-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_vehicle_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='drivers',
        ),
    ]
