# Generated by Django 4.1.10 on 2023-12-09 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0008_vehicle_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='drivers',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
    ]
