# Generated by Django 4.1.10 on 2023-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_vehicle_drivers_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles_images', verbose_name='Основное изображение'),
        ),
    ]
